# Generated by Django 3.2.4 on 2021-06-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='two_factor_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
