# Generated by Django 3.2.4 on 2021-06-27 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_two_factor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tfa_code_reset',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
