# Generated by Django 3.2.4 on 2021-06-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_tfa_code_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='two_factor_auth_status',
            field=models.BooleanField(default=False),
        ),
    ]
